spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rehabconnect
    username: rehab_user
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect